# Generated by Django 2.2 on 2019-06-15 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_room_name', models.CharField(blank=True, max_length=256)),
                ('persons', models.ManyToManyField(blank=True, related_name='chat_rooms', to='app_one.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_of_messaging', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app_one.ChatRoom')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_as_recipient', to='app_one.UserInfo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_as_sender', to='app_one.UserInfo')),
            ],
        ),
    ]
